
CREATE TABLE IF NOT EXISTS aluminium_passports (
    passport_id TEXT PRIMARY KEY,
    batch_id TEXT,
    bauxite_origin TEXT,
    mine_operator TEXT,
    date_of_extraction TEXT,
    refinery_location TEXT,
    refiner_id TEXT,
    smelting_energy_source TEXT,
    carbon_emissions_per_kg FLOAT,
    alloy_composition TEXT,
    trace_metals TEXT,
    manufacturer_id TEXT,
    process_type TEXT,
    manufactured_product TEXT,
    product_weight FLOAT,
    energy_used FLOAT,
    manufacturing_emissions FLOAT,
    transport_mode TEXT,
    distance_travelled FLOAT,
    logistics_partner_id TEXT,
    shipment_date TEXT,
    recycled_content_percent FLOAT,
    recycling_date TEXT,
    recycler_id TEXT,
    recycling_method TEXT,
    times_recycled INT,
    certification_agency TEXT,
    esg_score FLOAT,
    compliance_standards TEXT,
    date_of_certification TEXT,
    verifier_signature TEXT
);
